#!/usr/bin/env bash
# Turn a waitlist signup into a running Coil instance.
#
#   ops/new-firm.sh <slug> "<Firm Name>" <owner-email>
#   ops/new-firm.sh --dry-run <slug> "<Firm Name>" <owner-email>
#
# Run this ON the VPS. It creates the app directory, a firm-only .env, DNS, the
# container and that firm's cron jobs, then waits until the site answers.
#
# Two traps this script exists to avoid, both learned the hard way on this host:
#   1. Traefik keys routers, services and middlewares by NAME across every container
#      on the machine. Two firms sharing a name makes Traefik resolve the wrong
#      backend and answer 503. Every name here is namespaced with the firm slug.
#   2. The container runs as a non-root user. A root-owned data directory fails with
#      EACCES at the first write, so ownership is set explicitly.
set -euo pipefail

BASE_DOMAIN="${COIL_BASE_DOMAIN:-coil.legal}"
ZONE_ID="${COIL_ZONE_ID:-6ba7ed6eec107adbde335ed1c299d8e6}"   # coil.legal
VPS_IP="${COIL_VPS_IP:-204.168.134.211}"
APPS_DIR="${COIL_APPS_DIR:-/home/deploy/apps}"
SOURCE_APP="${COIL_SOURCE_APP:-$APPS_DIR/demo.coil.legal}"   # code and SMTP settings come from here
CF_TOKEN_FILE="${COIL_CF_TOKEN_FILE:-/root/.cloudflare-token}"

DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && { DRY_RUN=1; shift; }
SLUG="${1:-}"; FIRM="${2:-}"; EMAIL="${3:-}"
if [ -z "$SLUG" ] || [ -z "$FIRM" ] || [ -z "$EMAIL" ]; then
  echo "usage: new-firm.sh [--dry-run] <slug> \"<Firm Name>\" <owner-email>" >&2; exit 2
fi
case "$SLUG" in
  *[!a-z0-9-]*|-*|*-) echo "slug must be lowercase letters, digits and inner hyphens only" >&2; exit 2 ;;
esac

DOMAIN="$SLUG.$BASE_DOMAIN"
DIR="$APPS_DIR/$DOMAIN"
NS="coil-$SLUG"          # Traefik namespace, unique per firm

say() { echo "  $*"; }
run() { if [ "$DRY_RUN" = 1 ]; then echo "  would: $*"; else eval "$@"; fi; }

echo "Provisioning $FIRM"
say "domain:  https://$DOMAIN"
say "owner:   $EMAIL"
say "dir:     $DIR"
[ "$DRY_RUN" = 1 ] && say "(dry run, nothing will change)"

[ -d "$DIR" ] && { echo "refusing: $DIR already exists" >&2; exit 1; }
[ -d "$SOURCE_APP" ] || { echo "refusing: source app $SOURCE_APP not found" >&2; exit 1; }

# ---- code
run "mkdir -p '$DIR/data/uploads' '$DIR/data/pdf'"
run "rsync -a --exclude .git --exclude .venv --exclude __pycache__ --exclude data \
  --exclude .env --exclude node_modules --exclude .claude --exclude tests --exclude audit \
  '$SOURCE_APP/' '$DIR/'"

# ---- env. Never copy the source firm's SECRET_KEY: a shared key means one firm's
# session cookie is valid on another firm's instance.
if [ "$DRY_RUN" = 1 ]; then
  say "would: write $DIR/.env with a fresh SECRET_KEY and the SMTP block from $SOURCE_APP"
else
  SECRET="$(openssl rand -hex 32)"
  {
    echo "# $FIRM. Provisioned $(date -u +%F) by ops/new-firm.sh"
    echo "SECRET_KEY=$SECRET"
    echo "DOMAIN=$DOMAIN"
    echo "BASE_URL=https://$DOMAIN"
    echo "DATABASE_URL=sqlite:////app/data/practice.db"
    echo "COIL_SKIP_INSTALL_KEY=1   # hosted: the key gate is for self-installs"
    echo ""
    echo "# Email, shared relay account."
    grep -E "^(SMTP_HOST|SMTP_PORT|SMTP_USER|SMTP_PASS|MAIL_FROM)=" "$SOURCE_APP/.env" || true
    echo ""
    echo "# The firm's own accounts. Blank until they supply them; every feature that"
    echo "# needs one degrades with an explanation rather than breaking."
    echo "STRIPE_SECRET_KEY="
    echo "STRIPE_PUBLISHABLE_KEY="
    echo "STRIPE_WEBHOOK_SECRET="
    echo "TWILIO_ACCOUNT_SID="
    echo "TWILIO_AUTH_TOKEN="
    echo "TWILIO_FROM_NUMBER="
    echo "OPENROUTER_API_KEY="
    echo "ANTHROPIC_API_KEY="
    echo "COURTLISTENER_TOKEN="
  } > "$DIR/.env"
  chmod 600 "$DIR/.env"
  chown -R 1000:1000 "$DIR/data"      # the container runs as a non-root user
  say "wrote .env (600) and set data ownership"
fi

# ---- compose, with per-firm Traefik names
if [ "$DRY_RUN" = 1 ]; then
  say "would: write $DIR/docker-compose.yml with Traefik names namespaced '$NS'"
else
  cat > "$DIR/docker-compose.yml" <<YML
# $FIRM. Generated by ops/new-firm.sh. Traefik names are namespaced per firm because
# Traefik keys them across every container on this host; sharing one answers 503.
services:
  web:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.http.routers.$NS.rule=Host(\`$DOMAIN\`)
      - traefik.http.routers.$NS.entrypoints=https
      - traefik.http.routers.$NS.tls.certresolver=letsencrypt
      - traefik.http.services.$NS.loadbalancer.server.port=8000
      - traefik.http.routers.$NS-http.rule=Host(\`$DOMAIN\`)
      - traefik.http.routers.$NS-http.entrypoints=http
      - traefik.http.routers.$NS-http.middlewares=$NS-redirect
      - traefik.http.middlewares.$NS-redirect.redirectscheme.scheme=https
networks:
  coolify:
    external: true
YML
  say "wrote docker-compose.yml (Traefik namespace: $NS)"
fi

# ---- DNS. A proxied wildcard *.$BASE_DOMAIN covers every firm, so there is normally
# nothing to do here. Cloudflare's free certificate covers one level of subdomain, which
# is why firms live on $BASE_DOMAIN rather than two levels down under another domain.
if [ "$DRY_RUN" = 1 ]; then
  say "would: check DNS resolves (a wildcard *.$BASE_DOMAIN should already cover it)"
else
  if getent hosts "$DOMAIN" >/dev/null 2>&1 || host "$DOMAIN" >/dev/null 2>&1; then
    say "DNS resolves (wildcard)"
  elif [ -f "$CF_TOKEN_FILE" ]; then
    TOK="$(tr -d '[:space:]' < "$CF_TOKEN_FILE")"
    curl -s -X POST -H "Authorization: Bearer $TOK" -H "Content-Type: application/json" \
      "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
      --data "{\"type\":\"A\",\"name\":\"$SLUG\",\"content\":\"$VPS_IP\",\"proxied\":true,\"ttl\":1,\"comment\":\"Coil: $FIRM\"}" >/dev/null \
      && say "DNS record created for $DOMAIN"
  else
    say "WARNING: $DOMAIN does not resolve yet and no Cloudflare token is on this host."
    say "         Add a proxied wildcard A record *.$BASE_DOMAIN -> $VPS_IP once, and every"
    say "         future firm needs no DNS step at all."
  fi
fi

# ---- start
if [ "$DRY_RUN" = 1 ]; then
  say "would: docker compose up -d --build, then wait for the site to answer"
else
  ( cd "$DIR" && docker compose up -d --build >/dev/null 2>&1 ) || { echo "  ERROR: container failed to build or start" >&2; exit 1; }
  say "container started, waiting for it to answer"
  ok=0
  for i in $(seq 1 20); do
    code="$(curl -sk --resolve "$DOMAIN:443:127.0.0.1" "https://$DOMAIN/login" -o /dev/null -w '%{http_code}' --max-time 10 || true)"
    # A brand new instance has no users, so /login redirects to /setup. Both mean it is up.
    [ "$code" = "200" ] || [ "$code" = "302" ] && { ok=1; break; }
    sleep 5
  done
  [ "$ok" = 1 ] && say "site answers on the origin" || { echo "  ERROR: site did not answer, check: cd $DIR && docker compose logs web" >&2; exit 1; }
fi

# ---- cron, appended without disturbing what is already there
CRON_JOBS="15 7|agenda
30 7|reminders
0 8|sequences
*/10 *|emailin
*/15 *|webhooks
0 6 1 * *|interest
45 6|monthly_invoicing
0 5|case_audit
0 9|payment_plans
0 10|voice_reminders"
if [ "$DRY_RUN" = 1 ]; then
  say "would: add 10 cron jobs for $DOMAIN"
else
  TMP="$(mktemp)"; crontab -l 2>/dev/null > "$TMP" || true
  added=0
  while IFS='|' read -r when cmd; do
    [ -z "$cmd" ] && continue
    case "$when" in
      "0 6 1 * *") sched="0 6 1 * *" ;;
      "*/10 *")    sched="*/10 * * * *" ;;
      "*/15 *")    sched="*/15 * * * *" ;;
      *)           sched="$when * * *" ;;
    esac
    line="$sched cd $DIR && docker compose exec -T web python -m app.cli $cmd >> data/cron.log 2>&1"
    grep -qF "$DIR && docker compose exec -T web python -m app.cli $cmd " "$TMP" || { echo "$line" >> "$TMP"; added=$((added+1)); }
  done <<< "$CRON_JOBS"
  crontab "$TMP"; rm -f "$TMP"
  say "cron: $added job(s) added"
fi

echo
echo "Done. Send the firm:"
echo "  Your Coil is at https://$DOMAIN"
echo "  Open it and create the owner account with $EMAIL. You choose the password."
echo "  Payments and texting need your own Stripe and Twilio keys, added under Settings."
echo
echo "  AI is bring-your-own-key. The firm adds its own under Settings, AI, and pays the"
echo "  model maker directly. Do NOT put an operator key in $DIR/.env: every AI call that"
echo "  firm makes would be billed to whoever owns it. We cover the server, not inference."
[ "$DRY_RUN" = 1 ] && echo "(dry run: nothing was actually created)"
